'use strict';
(() => {
 const C=window.PTR_CONTENT,L=window.PTR_LEGAL,$=(s,root=document)=>root.querySelector(s),$$=(s,root=document)=>[...root.querySelectorAll(s)];
 const icon=(name,size=18)=>`<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.45" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${window.PTR_ICONS[name]||window.PTR_ICONS.arrow}</svg>`;
 const escape=(v)=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let toastTimer,selectedService=0,portalTab='assets',query='',statusFilter='all',quoteStep=1,lastAnchor='#top';
 function notify(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>{$('#toast').hidden=true;},4500);}
 function saveFile(filename,content,type='text/plain;charset=utf-8'){const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=filename;a.hidden=true;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function openDialog(dialog){if(!dialog.open)dialog.showModal();}
 function setMenu(open){$('#mega-menu').hidden=!open;$('#services-menu-toggle').setAttribute('aria-expanded',String(open));$('#mobile-menu-toggle').setAttribute('aria-expanded',String(open));$('#mobile-menu-toggle').setAttribute('aria-label',open?'Close navigation':'Open navigation');}
 $('#services-menu-toggle').addEventListener('click',()=>setMenu($('#mega-menu').hidden));
 $('#mobile-menu-toggle').addEventListener('click',()=>setMenu($('#mega-menu').hidden));
 document.addEventListener('click',e=>{if(!e.target.closest('.site-header'))setMenu(false);});
 document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#mega-menu').hidden){setMenu(false);(innerWidth<700?$('#mobile-menu-toggle'):$('#services-menu-toggle')).focus();}});
 $('#mega-links').innerHTML=C.services.map((s,i)=>`<button data-service="${i}">${escape(s.name)} ${icon('arrow')}</button>`).join('')+`<a href="#industries">Industries</a><a href="#why-phoenix">Why Phoenix</a><a href="#resources">Insights</a><a href="#portal">Client portal preview</a>`;
 $('#service-list').innerHTML=C.services.map((s,i)=>`<button class="service-row${i===0?' active':''}" data-select-service="${i}" aria-pressed="${i===0}"><span class="num">${String(i+1).padStart(2,'0')}</span><span class="name">${escape(s.name)}</span>${icon('arrow')}</button>`).join('');
 function selectService(i){selectedService=i;const s=C.services[i];$$('[data-select-service]').forEach((b,j)=>{b.classList.toggle('active',i===j);b.setAttribute('aria-pressed',String(i===j));});$('#feature-label').textContent=`${String(i+1).padStart(2,'0')} / ${s.name.toUpperCase()}`;$('#feature-title').textContent=s.short;$('#feature-body').textContent=s.body;}
 function showContent(kicker,title,html){$('#content-kicker').textContent=kicker;$('#content-title').textContent=title;$('#content-body').innerHTML=html;openDialog($('#content-dialog'));$('#content-dialog').scrollTop=0;}
 function showService(i){const s=C.services[i];if(!s)return;setMenu(false);showContent('Explore the lifecycle',s.name,`<p>${s.body}</p><h3>${s.short}</h3><p>${s.detail}</p><h3>What to align on</h3><ul>${s.deliverables.map(d=>`<li>${escape(d)}</li>`).join('')}</ul><button class="button ink" data-quote data-quote-service="${i}">Discuss this service ${icon('arrow')}</button><p class="micro" style="margin-top:25px">Service-content draft based on the supplied website outline. Scope, location, methods, and deliverables require confirmation. No certification is represented.</p>`);}
 $('#service-detail-button').addEventListener('click',()=>showService(selectedService));
 function enableRovingTabs(container,activate){container.addEventListener('keydown',e=>{const tabs=$$('[role="tab"]',container),current=tabs.indexOf(document.activeElement);if(current<0)return;let next=current;if(e.key==='ArrowRight'||e.key==='ArrowDown')next=(current+1)%tabs.length;else if(e.key==='ArrowLeft'||e.key==='ArrowUp')next=(current-1+tabs.length)%tabs.length;else if(e.key==='Home')next=0;else if(e.key==='End')next=tabs.length-1;else return;e.preventDefault();activate(next);tabs[next].focus();});}
 $('#process-tabs').innerHTML=C.process.map((s,i)=>`<button class="process-tab" role="tab" aria-selected="false" tabindex="-1" aria-controls="process-panel" id="process-tab-${i}" data-process="${i}"><span>${String(i+1).padStart(2,'0')}</span><strong>${escape(s.name)}</strong></button>`).join('');
 function selectProcess(i){const s=C.process[i];$$('[data-process]').forEach((b,j)=>{b.classList.toggle('active',i===j);b.setAttribute('aria-selected',String(i===j));b.tabIndex=i===j?0:-1;});$('#process-panel').setAttribute('aria-labelledby',`process-tab-${i}`);['title','body','event','record','foot'].forEach(k=>{$('#process-'+k).textContent=s[k];});}
 enableRovingTabs($('#process-tabs'),selectProcess);selectProcess(0);
 $('#industry-tabs').innerHTML=C.industries.map((s,i)=>`<button role="tab" id="industry-tab-${i}" aria-controls="industry-panel" aria-selected="false" tabindex="-1" data-industry="${i}">${icon(s.icon,24)}${escape(s.name)}</button>`).join('');
 function selectIndustry(i){$('#industry-copy').textContent=C.industries[i].body;$('#industry-panel').setAttribute('aria-labelledby',`industry-tab-${i}`);$$('[data-industry]').forEach((b,j)=>{b.classList.toggle('active',i===j);b.setAttribute('aria-selected',String(i===j));b.tabIndex=i===j?0:-1;});}
 enableRovingTabs($('#industry-tabs'),selectIndustry);selectIndustry(0);
 $('#resource-grid').innerHTML=C.resources.map((r,i)=>`<button class="resource" data-resource="${i}"><span class="meta"><span>${r.type}</span><span>${r.time}</span></span><h3>${r.title}</h3><p>${r.summary}</p><span class="resource-arrow">Read the guide ${icon('arrow')}</span></button>`).join('');
 function showResource(i){const r=C.resources[i];if(!r)return;showContent(r.type+' · '+r.time,r.title,`<p>${r.summary}</p>${r.body}<button class="button outline" data-guide-download="${i}">Save a reading copy ${icon('download')}</button>`);}
 function filteredAssets(){return C.assets.filter(a=>(query===''||`${a.name} ${a.serial} ${a.type}`.toLowerCase().includes(query.toLowerCase()))&&(statusFilter==='all'||a.status===statusFilter));}
 function renderAssetRows(){const list=filteredAssets();$('#asset-rows').innerHTML=list.length?list.map(a=>`<tr><td>${escape(a.name)}<span class="serial">${a.serial}</span></td><td>${a.type}</td><td><span class="status${a.status==='Testing & grading'?' progress':''}">${a.status}</span></td></tr>`).join(''):'<tr><td colspan="3" class="no-results">No demo assets match your search.</td></tr>';$('#asset-count').textContent=`Showing ${list.length} of 4 demonstration assets`;}
 function selectPortal(tab){portalTab=tab;$$('[data-portal-tab]').forEach(b=>{const selected=b.dataset.portalTab===tab;b.classList.toggle('active',selected);b.setAttribute('aria-selected',String(selected));b.tabIndex=selected?0:-1;});$('#portal-panel').setAttribute('aria-labelledby','portal-'+tab);
  if(tab==='assets'){$('#portal-panel').innerHTML=`<div class="portal-heading"><h3>Asset overview</h3><button class="mini-button" id="export-assets">${icon('download',13)} Export sample</button></div><div class="portal-tools"><div class="search-wrap">${icon('search',14)}<input id="asset-search" type="search" aria-label="Search demonstration assets" placeholder="Search assets or serial numbers" value="${escape(query)}"></div><label>Status <select id="asset-status"><option value="all">All statuses</option><option>Ready for remarketing</option><option>Testing & grading</option><option>Processing complete</option></select></label></div><div class="table-scroll"><table><caption class="sr-only">Synthetic demonstration asset records, not customer data</caption><thead><tr><th scope="col">Asset / serial number</th><th scope="col">Type</th><th scope="col">Status</th></tr></thead><tbody id="asset-rows"></tbody></table></div><div class="portal-foot"><span id="asset-count" role="status" aria-live="polite"></span><span>Illustrative records only</span></div>`;$('#asset-status').value=statusFilter;$('#asset-search').addEventListener('input',e=>{query=e.target.value;renderAssetRows();});$('#asset-status').addEventListener('change',e=>{statusFilter=e.target.value;renderAssetRows();});$('#export-assets').addEventListener('click',()=>{const rows=[['DEMONSTRATION ONLY — NOT AN OPERATIONAL REPORT'],['Asset','Serial','Type','Status'],...filteredAssets().map(a=>[a.name,a.serial,a.type,a.status])];const csv=rows.map(r=>r.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\r\n');saveFile('Phoenix-DEMO-assets.csv','\uFEFF'+csv,'text/csv;charset=utf-8');notify('Sample CSV prepared. All records are demonstration data.');});renderAssetRows();}
  else if(tab==='documents'){$('#portal-panel').innerHTML=`<div class="portal-heading"><h3>Document workspace</h3><span class="demo-pill">Preview</span></div><p class="micro muted" style="margin:18px 0">Explore the proposed document experience. These are format examples, not client records or certificates.</p><div class="document-row">${icon('file',23)}<div>Sample inventory report<small>Demonstration format · TXT</small></div><button class="mini-button" data-sample-download="inventory">Preview ${icon('download',12)}</button></div><div class="document-row">${icon('shield',23)}<div>Data-handling record fields<small>Field checklist · Not a certificate</small></div><button class="mini-button" data-sample-download="data">Preview ${icon('download',12)}</button></div><div class="document-row">${icon('file',23)}<div>Project closeout checklist<small>Planning document · TXT</small></div><button class="mini-button" data-sample-download="closeout">Preview ${icon('download',12)}</button></div><div class="portal-foot"><span>No live document system connected</span><span>Illustrative content</span></div>`;}
  else{$('#portal-panel').innerHTML=`<div class="portal-heading"><h3>Recovered-value reporting</h3><span class="demo-pill">Synthetic example</span></div><div class="report-summary"><div><strong>$390</strong><span>Illustrative gross recovery</span></div><div><strong>2 / 4</strong><span>Demo assets eligible for remarketing</span></div></div><p class="micro muted">This example shows how reporting could separate asset outcomes and financial results. These figures are invented for the interface, not achieved returns or an estimate for your equipment.</p><div class="document-row">${icon('circle',23)}<div>Business laptop · DEMO-LT-001<small>Illustrative amount</small></div><strong>$180</strong></div><div class="document-row">${icon('circle',23)}<div>Business laptop · DEMO-LT-003<small>Illustrative amount</small></div><strong>$210</strong></div><div class="portal-foot"><span>Actual values depend on inspection and agreed terms.</span></div>`;}
 }
 enableRovingTabs($('.portal-tabs'),i=>selectPortal(['assets','documents','value'][i]));selectPortal('assets');
 /* Consent: no vendor loaders are installed. Signals override optional choices. */
 const KEY='ptr_privacy_v1',VERSION=1,TTL=180*24*60*60*1000;
 const privacySignal=()=>navigator.globalPrivacyControl===true||navigator.doNotTrack==='1'||window.doNotTrack==='1';
 let stored=null,storageAvailable=true;
 function readConsent(){let raw;try{raw=localStorage.getItem(KEY);}catch{storageAvailable=false;return null;}if(!raw)return null;let v;try{v=JSON.parse(raw);}catch{return null;}if(!v||v.version!==VERSION||v.necessary!==true||typeof v.analytics!=='boolean'||typeof v.marketing!=='boolean'||!Number.isFinite(v.timestamp)||!Number.isFinite(v.expiresAt)||v.timestamp>Date.now()+60000||v.expiresAt<=Date.now()||v.expiresAt-v.timestamp>TTL+1000)return null;return v;}
 stored=readConsent();
 function currentConsent(){return {necessary:true,analytics:!privacySignal()&&Boolean(stored?.analytics),marketing:!privacySignal()&&Boolean(stored?.marketing)};}
 function saveConsent(analytics,marketing){const signal=privacySignal(),now=Date.now();stored={version:VERSION,necessary:true,analytics:!signal&&!!analytics,marketing:!signal&&!!marketing,signal:signal?'browser-opt-out':'none',timestamp:now,expiresAt:now+TTL};try{localStorage.setItem(KEY,JSON.stringify(stored));storageAvailable=true;}catch{storageAvailable=false;}$('#cookie-banner').hidden=true;$('#consent-dialog').close();window.dispatchEvent(new CustomEvent('ptr:consent-change',{detail:currentConsent()}));notify(storageAvailable?'Privacy preferences saved. No optional trackers run in this preview.':'Preferences applied for this page. Browser storage is unavailable.');}
 function openConsent(){const state=currentConsent(),signal=privacySignal();$('#consent-analytics').checked=state.analytics;$('#consent-marketing').checked=state.marketing;$('#consent-analytics').disabled=signal;$('#consent-marketing').disabled=signal;$('#signal-note').hidden=!signal;$('#storage-note').hidden=storageAvailable;openDialog($('#consent-dialog'));}
 $('#cookie-banner').hidden=!!stored;
 $('#accept-cookies').disabled=privacySignal();
 if(privacySignal()&&stored&&(stored.analytics||stored.marketing)){const now=Date.now();stored={...stored,analytics:false,marketing:false,signal:'browser-opt-out',timestamp:now,expiresAt:now+TTL};try{localStorage.setItem(KEY,JSON.stringify(stored));}catch{storageAvailable=false;}}
 $('#reject-cookies').addEventListener('click',()=>saveConsent(false,false));$('#accept-cookies').addEventListener('click',()=>saveConsent(true,true));$('#consent-reject').addEventListener('click',()=>saveConsent(false,false));$('#consent-save').addEventListener('click',()=>saveConsent($('#consent-analytics').checked,$('#consent-marketing').checked));
 window.addEventListener('storage',e=>{if(e.key===KEY){stored=readConsent();$('#cookie-banner').hidden=!!stored;if($('#consent-dialog').open)openConsent();}});
 /* Legal hash routes provide shareable, offline-safe documents. */
 function route(){const match=location.hash.match(/^#\/legal\/([a-z]+)$/);if(match&&L[match[1]]){const d=L[match[1]];showContent(d.subtitle,d.title,`<p class="doc-date">Prepared for executive review · September 2026 · No production effective date</p>${d.html}<div class="legal-source"><p><strong>Source reference</strong></p><a href="${d.source}" target="_blank" rel="noopener noreferrer">${d.sourceName}</a><p>Reviewed September 10, 2026. Preview-specific additions and omissions are documented in the handoff notes. This is not a wholesale replacement of the parent document.</p></div>`);}else{lastAnchor=location.hash||'#top';}}
 window.addEventListener('hashchange',()=>{if(!location.hash.startsWith('#/legal/')&&$('#content-dialog').open)$('#content-dialog').close();route();});
 $('#content-dialog').addEventListener('close',()=>{if(location.hash.startsWith('#/legal/'))history.replaceState(null,'',lastAnchor);});
 function showQuote(service){setMenu(false);if($('#content-dialog').open)$('#content-dialog').close();if(Number.isInteger(service))$('#q-service').value=C.services[service]?.name||'';openDialog($('#quote-dialog'));setQuoteStep(quoteStep);}
 C.services.forEach(s=>{const o=document.createElement('option');o.textContent=s.name;$('#q-service').append(o);});
 function setQuoteStep(n){quoteStep=n;[1,2,3].forEach(i=>{$('#quote-step-'+i).hidden=i!==n;$('#step-label-'+i).classList.toggle('active',i===n);if(i===n)$('#step-label-'+i).setAttribute('aria-current','step');else $('#step-label-'+i).removeAttribute('aria-current');});if(n===1)$('#q-service').focus();else if(n===2)$('#q-name').focus();else $('#quote-download').focus();}
 function validateStep(n){const controls=$$('input,select,textarea',$('#quote-step-'+n));for(const field of controls){if(!field.checkValidity()){field.reportValidity();field.focus();return false;}if(field.required&&field.value.trim()===''){field.setCustomValidity('Please complete this field.');field.reportValidity();field.addEventListener('input',()=>field.setCustomValidity(''),{once:true});return false;}}return true;}
 function projectSummary(){const val=id=>$('#q-'+id).value.trim();return `PHOENIX TECH REFRESH — PROJECT INQUIRY\nExecutive preview: prepared locally, not submitted.\n\nService: ${val('service')}\nAsset quantity: ${val('volume')}\nLocation: ${val('location')}\nTiming: ${val('timing')}\n\nName: ${val('name')}\nCompany: ${val('company')}\nEmail: ${val('email')}\nPhone: ${val('phone')||'Not provided'}\n\nProject notes: ${val('notes')||'None provided'}\n\nPlease route this inquiry to the Phoenix Tech Refresh team.\nNo service, valuation, pickup, or terms have been accepted.`;}
 $('#quote-form').addEventListener('submit',e=>{e.preventDefault();if(quoteStep===1)$('#quote-next').click();else if(quoteStep===2)$('#quote-review').click();});
 $('#quote-next').addEventListener('click',()=>{if(validateStep(1))setQuoteStep(2);});$('#quote-back').addEventListener('click',()=>setQuoteStep(1));$('#quote-edit').addEventListener('click',()=>setQuoteStep(2));$('#quote-review').addEventListener('click',()=>{if(!validateStep(2))return;const summary=projectSummary();$('#quote-summary').textContent=summary;$('#quote-mail').href='mailto:info@it1.com?subject='+encodeURIComponent('Phoenix Tech Refresh — project inquiry')+'&body='+encodeURIComponent(summary);setQuoteStep(3);});$('#quote-download').addEventListener('click',()=>{saveFile('Phoenix-project-summary.txt',projectSummary());notify('Project summary saved locally. Nothing has been submitted.');});
 const sampleDocs={inventory:'SAMPLE INVENTORY REPORT — DEMONSTRATION ONLY\nNot an operational record.\n\nSuggested fields: project reference, serial number, asset type, manufacturer, model, quantity, location, condition, status, disposition route.\nUse the actual asset system as the production source of truth.',data:'DATA-HANDLING RECORD FIELD CHECKLIST\nDEMONSTRATION ONLY — NOT A CERTIFICATE\n\nDiscuss: asset identifier; media type; required method; verification result; exception status; date; authorized technician or reviewer; final disposition.\nRequired fields and applicable methods must be confirmed in the service agreement.',closeout:'PROJECT CLOSEOUT CHECKLIST — PLANNING EXAMPLE\nNot proof of service.\n\nReconcile opening inventory and final outcomes.\nExplain exceptions.\nProvide agreed data-handling evidence.\nSummarize reuse and recycling outcomes.\nReconcile fees and any value returned.\nConfirm record delivery and retention responsibilities.'};
 $('#review-notes-button').addEventListener('click',()=>showContent('Executive review · September 2026','Executive preview. Not a production release.',`<p>This is a working desktop-first homepage, not a static screenshot. Menus, service exploration, lifecycle steps, portal filters and exports, resources, FAQs, the project form, and cookie controls work in your browser.</p><h3>Brand and content</h3><p>The approved Premium Corporate #2 symbol is used. Phoenix is presented as an iT1 company per the project owner. Concept photographs do not document actual staff or facilities. There are no invented client logos, testimonials, certifications, company operating statistics, or environmental-performance claims.</p><h3>Demonstration boundaries</h3><p>The portal is an interface preview with explicitly synthetic records. Project requests are prepared in-browser and are not submitted; an email draft opens only on your instruction. Analytics, advertising, CRM, authentication, and live asset-system integrations are not installed.</p><h3>Legal before launch</h3><p>Privacy and terms are source-informed drafts for review. Confirm the legal operator, production domain, controller, contact routing, actual data practices, vendors, retention, and final legal wording. Cookie notices describe only this implementation. The parent policy contains legacy and potentially conflicting tracking language; it has not been silently rewritten as a production policy.</p><h3>Reference sources</h3><ul><li>The supplied Phoenix Tech Refresh Website Development Outline, September 10, 2026</li><li><a href="https://it1.com/privacy-policy/" target="_blank" rel="noopener noreferrer">iT1 Privacy Policy</a></li><li><a href="https://it1.com/40-ca-013-2-it1-website-terms-of-use_10-30-2023/" target="_blank" rel="noopener noreferrer">iT1 Website Terms of Use</a></li><li><a href="https://it1.com/contact-us/" target="_blank" rel="noopener noreferrer">iT1 contact information</a></li><li><a href="https://sagese.com/" target="_blank" rel="noopener noreferrer">Sage</a>, <a href="https://techbrosaz.com/" target="_blank" rel="noopener noreferrer">TechBros</a>, and <a href="https://er2.com/business-services/" target="_blank" rel="noopener noreferrer">ER2</a> as reference websites—not copied customer proof.</li></ul>`));
 document.addEventListener('click',e=>{const b=e.target.closest('button,a');if(!b)return;
  if(b.hasAttribute('data-close')){b.closest('dialog').close();return;}
  if(b.hasAttribute('data-consent')||b.hasAttribute('data-privacy-choices')){openConsent();return;}
  if(b.hasAttribute('data-compliance')){showQuote(1);$('#q-notes').value='Please discuss the current certification scope, insurance, data-handling methods, and downstream documentation relevant to our project.';return;}
  if(b.hasAttribute('data-quote')){e.preventDefault();showQuote(b.hasAttribute('data-quote-service')?Number(b.dataset.quoteService):undefined);return;}
  if(b.hasAttribute('data-service')){showService(Number(b.dataset.service));return;}
  if(b.hasAttribute('data-select-service')){selectService(Number(b.dataset.selectService));return;}
  if(b.hasAttribute('data-process')){selectProcess(Number(b.dataset.process));return;}
  if(b.hasAttribute('data-industry')){selectIndustry(Number(b.dataset.industry));return;}
  if(b.hasAttribute('data-resource')){showResource(Number(b.dataset.resource));return;}
  if(b.hasAttribute('data-portal-tab')){selectPortal(b.dataset.portalTab);return;}
  if(b.hasAttribute('data-sample-download')){saveFile('Phoenix-DEMO-'+b.dataset.sampleDownload+'.txt',sampleDocs[b.dataset.sampleDownload]);notify('Illustrative document prepared. Not a client record or certificate.');return;}
  if(b.hasAttribute('data-guide-download')){const r=C.resources[Number(b.dataset.guideDownload)],doc=new DOMParser().parseFromString(r.body,'text/html');const text=[...doc.body.children].map(el=>el.textContent).join('\n\n');saveFile('Phoenix-planning-guide-'+(Number(b.dataset.guideDownload)+1)+'.txt',r.title+'\n\n'+text+'\n\nPhoenix Tech Refresh — Executive website preview, September 2026.');return;}
  if(b.closest('#mega-menu')&&b.tagName==='A')setMenu(false);
 });
 // Clicking outside an open dialog closes it without accepting privacy choices.
 $$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target!==d)return;const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}));
 route();
})();
