/* Source-informed draft content. Operating claims and policy text require owner sign-off. */
window.PTR_CONTENT = {
 services: [
  {name:'IT asset disposition', short:'A better finish. A stronger next step.', body:'Bring collection, data handling, recovery, and reporting into one coordinated plan. Retire your technology without leaving the details to chance.', detail:'Start with the assets, locations, timing, and data-handling requirements. Build an agreed workflow for inventory, transport, sanitization, testing, remarketing or recycling, and final reporting.', deliverables:['An agreed scope and asset inventory','A documented disposition pathway','An engagement-specific reporting plan']},
  {name:'Data destruction & sanitization', short:'Your data stays your business.', body:'Set the data-handling requirements before equipment moves. Match the sanitization or destruction pathway to the media, sensitivity, and requirements of your organization.', detail:'The project specification calls for serialized tracking, media-appropriate sanitization, and engagement-level documentation. Method, onsite availability, verification, and certificate scope must be confirmed in the service agreement.', deliverables:['Media and data-sensitivity assessment','Agreed verification and exception handling','Required destruction or sanitization records']},
  {name:'IT asset remarketing', short:'Retired from your team. Not from possibility.', body:'Find the value in the hardware you no longer need. Testing, grading, and a considered resale strategy put reuse before unnecessary disposal.', detail:'A remarketing plan begins with make, model, age, specification, condition, ownership, and resale restrictions. Recovery estimates are subject to inspection, market demand, agreed fees, and final terms; no return is guaranteed.', deliverables:['Asset condition and eligibility review','A clear valuation and fee model','Itemized recovered-value reporting']},
  {name:'Data center decommissioning', short:'Complex infrastructure. One clear plan.', body:'Coordinate racks, servers, storage, removal windows, and sensitive media within a single decommissioning scope.', detail:'Define the equipment boundary, access permissions, live-system dependencies, maintenance windows, disconnection responsibilities, removal sequence, transport, and reporting before work starts.', deliverables:['Project scope and site-readiness plan','Asset and media reconciliation','Agreed removal and reporting milestones']},
  {name:'Reverse logistics & transport', short:'A clear chain from your door to ours.', body:'Plan collection and transport around your people, sites, and security requirements—not the other way around.', detail:'Document packaging, access, pickup windows, asset handover, carrier arrangements, and transit responsibilities. Confirm service geography and any special handling before scheduling.', deliverables:['Collection and packaging requirements','Documented custody handover','Receiving and exception reconciliation']},
  {name:'Onsite & field services', short:'The right support, where you need it.', body:'Shape an onsite engagement around your facilities, security policies, and operational schedule.', detail:'Onsite inventory, de-installation, and data-handling options depend on the location, equipment, and required methods. Confirm staffing, safety responsibilities, witnessing needs, and service availability during scoping.', deliverables:['Site access and safety requirements','Defined onsite responsibilities','Agreed completion evidence']},
  {name:'Responsible electronics recycling', short:'The end of a device. Not the end of responsibility.', body:'When reuse is no longer appropriate, establish a responsible recycling route and the documentation your organization needs.', detail:'Review reuse eligibility first, then confirm material categories, downstream arrangements, and reporting. Environmental results and certification coverage must be substantiated for the actual engagement.', deliverables:['Reuse-versus-recycling assessment','Defined downstream reporting expectations','Documented material disposition']},
  {name:'Buyback & trade-in programs', short:'Make room for what comes next.', body:'Explore how an equipment buyback or planned refresh program can support your next technology investment.', detail:'Provide the inventory, condition, timing, and ownership information for an assessment. Prices, payment timing, fees, and eligibility require an accepted written offer; the website does not create a binding valuation.', deliverables:['Inventory-based estimate','Agreed buyback terms','A clear settlement and reporting process']}
 ],
 process:[
  {name:'Plan & collect',title:'Good outcomes start before pickup.',body:'Align on your inventory, locations, schedule, data requirements, and what success looks like. Define the handover before equipment leaves your care.',event:'Collection plan agreed',record:'Scope, site access, and inventory requirements',foot:'You know the next step before the first handover.'},
  {name:'Secure custody',title:'Know what moved. Know what arrived.',body:'Reconcile the asset inventory across each agreed handover. Make exceptions visible rather than leaving your team to chase missing details.',event:'Asset handover recorded',record:'Serial-level inventory and receiving reconciliation',foot:'A documented pathway from collection to processing.'},
  {name:'Sanitize data',title:'The right method for the right media.',body:'Apply the agreed sanitization or destruction pathway, with verification and exception handling matched to your media and security requirements.',event:'Data-handling step recorded',record:'Agreed method, verification, and exception evidence',foot:'Method and documentation are set in the engagement scope.'},
  {name:'Test & grade',title:'See the potential in every eligible asset.',body:'Assess functional condition and resale suitability. Separate equipment with a useful next life from assets that need a different disposition route.',event:'Condition assessment recorded',record:'Function, condition, and reuse eligibility',foot:'Clear grading supports a considered recovery strategy.'},
  {name:'Recover value',title:'Give useful technology another chapter.',body:'Remarket or redeploy eligible equipment. Route remaining material for appropriate recycling, with economics and reporting agreed up front.',event:'Disposition pathway selected',record:'Remarketing, redeployment, or recycling route',foot:'Actual recovery depends on the equipment and agreement.'},
  {name:'Report & close',title:'Close the loop. Keep the evidence.',body:'Bring together the inventory, data-handling records, disposition outcomes, and financial reporting specified in your engagement.',event:'Reporting package assembled',record:'Asset outcomes, supporting records, and reconciliation',foot:'A clear closeout for IT, finance, and sustainability teams.'}
 ],
 industries:[
  {name:'Enterprise',icon:'building',body:'Coordinate refresh programs across teams and locations. Bring IT, procurement, finance, and sustainability into one agreed plan without creating another layer of work.'},
  {name:'Healthcare',icon:'heart',body:'Start with your information-security and procurement requirements. Define data handling, custody, reporting, and any required contractual protections before an asset is collected.'},
  {name:'Financial services',icon:'chart',body:'Keep the focus on sensitive data, controlled handovers, and documented outcomes. Scope the evidence your risk, compliance, and asset-management teams need.'},
  {name:'Education',icon:'school',body:'Plan around academic calendars, district or campus refresh cycles, and available budgets. Explore equipment reuse and buyback while documenting student-data handling requirements.'},
  {name:'Government',icon:'landmark',body:'Align disposition work with agency procurement, security, and documentation requirements. Confirm contract terms, authorized methods, and service scope before the project begins.'},
  {name:'Data centers',icon:'server',body:'Map complex removal dependencies, storage media, rack inventories, maintenance windows, and physical access. Build a practical plan before any infrastructure is disconnected.'}
 ],
 assets:[
  {name:'Business laptop',serial:'DEMO-LT-001',type:'Laptop',status:'Ready for remarketing',value:180},
  {name:'Rack server',serial:'DEMO-SV-002',type:'Server',status:'Testing & grading',value:0},
  {name:'Business laptop',serial:'DEMO-LT-003',type:'Laptop',status:'Ready for remarketing',value:210},
  {name:'Storage drive',serial:'DEMO-HD-004',type:'Storage',status:'Processing complete',value:0}
 ],
 resources:[
  {type:'Planning guide',time:'3 min read',title:'Before your next hardware refresh.',summary:'The questions that turn a device retirement into a better business decision.',body:'<h3>Start with the outcome</h3><p>Decide what matters most for this project: reducing data risk, meeting a move-out date, recovering asset value, or consolidating reporting. Agree on priorities with IT, procurement, finance, and sustainability before requesting a quote.</p><h3>Make the inventory useful</h3><p>Collect make, model, serial number, quantity, location, condition, ownership, and known restrictions. Separate data-bearing assets from peripherals, and identify damaged batteries or other items that need special handling.</p><h3>Agree on evidence</h3><p>Ask what will document each handover and the final outcome. Discuss the records required by your internal policies, rather than assuming every engagement includes the same report.</p><h3>Know the commercial model</h3><p>Clarify inspection assumptions, handling and service fees, revenue sharing, payment timing, and what happens to equipment that cannot be resold. A higher headline estimate is not automatically a better net outcome.</p><h3>Leave with a plan</h3><p>Request a written scope that names responsibilities, milestones, evidence, and exception handling. This guide is original editorial planning content, not a claim that any particular certification or service is available.</p>'},
  {type:'Data & accountability',time:'2 min read',title:'The record matters as much as the removal.',summary:'What to discuss about custody, verification, and final documentation.',body:'<h3>Clarify the handover</h3><p>Document who is responsible for an asset at each stage and what evidence records the transfer. Align the expected inventory with what is actually collected and received.</p><h3>Make exceptions visible</h3><p>A missing serial number, unexpected device, damaged item, or unsuccessful sanitization should have a defined review path. Agree who receives an exception, who decides what happens next, and how the decision is recorded.</p><h3>Ask for the right evidence</h3><p>Discuss media type, required data-handling method, verification, and the records your organization needs. Confirm whether records will identify individual assets, batches, or both.</p><h3>Keep the final reconciliation</h3><p>A useful closeout connects the opening inventory to documented outcomes and explains exceptions. Ask for an example reporting format during procurement and agree on retention and delivery requirements in writing.</p><p>This is a project-scoping guide, not legal advice or a certification statement.</p>'},
  {type:'Value & circularity',time:'2 min read',title:'Retired does not have to mean finished.',summary:'A practical look at testing, reuse, and responsible disposition.',body:'<h3>Assess before assuming</h3><p>An asset that no longer meets one team’s needs may still be useful elsewhere. Make, model, age, performance, condition, ownership, and security restrictions all affect whether reuse is appropriate.</p><h3>Separate gross price from net recovery</h3><p>Ask how testing, repair, transport, resale fees, and other agreed costs affect the final amount returned. Confirm how pricing is established and when a settlement becomes final.</p><h3>Respect the data boundary</h3><p>Reuse decisions must follow the agreed data-handling requirements. A resale opportunity does not override security policy or a contractual restriction.</p><h3>Document the remaining route</h3><p>For assets that cannot be reused, agree the recycling pathway and the reporting that supports your internal sustainability work. Avoid treating unverified projections as measured environmental results.</p><p>Original editorial guidance prepared for this website preview. Actual eligibility and recovered value depend on inspection, market conditions, and contract terms.</p>'}
 ]
};
window.PTR_LEGAL = {
 privacy:{title:'Privacy Policy',subtitle:'Phoenix Tech Refresh · Executive-review draft',source:'https://it1.com/privacy-policy/',sourceName:'iT1 Privacy Policy',html:`
 <p class="draft-notice"><strong>Draft for iT1 legal review.</strong> This notice describes the executive preview. It is not approved for public launch. The registered site operator, privacy controller, production vendors, retention schedule, and rights-request routing still require confirmation.</p>
 <h3>Who this notice concerns</h3><p>Phoenix Tech Refresh is presented as an iT1 company based on the project owner’s direction. The brand name is not a representation that a separate legal entity with that name has been registered. The parent policy identifies iT1; the entity operating this future site must be confirmed before publication.</p>
 <h3>What happens in this preview</h3><p>The local preview displays business information and illustrative portal records. Its project form processes what you type only in the current browser session. It does not submit your details to a server, CRM, analytics service, or marketing platform. Refreshing the page clears the form state.</p><p>You may explicitly download a project summary or open a draft in your own email application. A downloaded summary remains on your device. An email is not sent until you choose to send it using your email provider; that provider’s terms and privacy practices apply.</p>
 <h3>Browser storage and tracking</h3><p>This build stores a versioned privacy-preference record in local storage, described in the Cookie Policy. No advertising, analytics, social pixels, embedded maps, chat vendors, remote fonts, or other optional tracking services are installed. Selecting an optional preference records the choice only; it does not activate a service in this preview.</p><p>If someone hosts this preview over HTTP, the host may create technical access logs according to its configuration. That hosting environment has not been inventoried by this notice. Opening the standalone file does not contact a web host.</p>
 <h3>Parent-policy topics retained for review</h3><p>iT1’s policy addresses information supplied through forms and transactions, service communications, permitted disclosures, retention, children’s privacy, browser tracking preferences, and California privacy requests. Those topics remain part of the production review. Its descriptions of purchasing, payment processing, AdRoll, and Google technologies have not been transplanted as claims about this preview.</p>
 <h3>Your choices and requests</h3><p>Use Cookie preferences to change this browser’s choices. Global Privacy Control and Do Not Track signals keep optional categories off. Browser storage controls can also remove the record. These local controls do not submit a company-wide access, correction, deletion, or other rights request.</p><p>For iT1’s published rights procedures, consult the parent policy. Its published contact route includes <a href="tel:+18777775995">(877) 777-5995</a>. Confirm the Phoenix-specific controller and request process with iT1 before launch. Do not send identity documents, credentials, patient data, or other sensitive information through the project form.</p>
 <h3>Before the public site launches</h3><p>iT1 legal and the implementation team must reconcile the actual collection categories, purposes, vendors, international handling, retention, request workflow, and any state or regional notice requirements. The preview’s no-tracking behavior must not be assumed to describe a later production integration.</p>`},
 terms:{title:'Terms of Use',subtitle:'Phoenix Tech Refresh · Executive-review draft',source:'https://it1.com/40-ca-013-2-it1-website-terms-of-use_10-30-2023/',sourceName:'iT1 Website Terms of Use',html:`
 <p class="draft-notice"><strong>Draft adaptation—not an approved agreement.</strong> Prepared for internal executive review using iT1’s Website Terms of Use as the reference. iT1 legal must approve the operator, party definitions, limitations, and final wording before public use.</p>
 <h3>1. Scope and parties</h3><p>This preview uses the Phoenix Tech Refresh brand. The parent terms define iT1 collectively through iT1 Source LLC, iT1 Consulting LLC, iT1 International Holdings, Inc., and affiliates. Ownership of a brand does not by itself establish which entity operates this website or contracts for services; that determination remains with iT1 legal.</p>
 <h3>2. Permitted use and ownership</h3><p>Use the website lawfully and respect the content and marks of their owners. Reproduction and reuse may require permission. External destinations have their own terms and are not controlled by this preview.</p>
 <h3>3. Preview materials are not operational records</h3><p>Portal records, status events, and recovery amounts displayed here are synthetic demonstration data. They are not customer information, a valuation, a certificate of destruction, proof of a completed service, or evidence of a certification. Concept imagery is illustrative and does not document an actual Phoenix facility or employee.</p>
 <h3>4. No transaction or service acceptance</h3><p>Preparing a project summary does not place an order, schedule a pickup, reserve service capacity, transfer ownership, or form an ITAD services contract. Scope, geography, methods, fees, financial recovery, reporting, insurance, and service levels must be confirmed in a separate accepted agreement.</p>
 <h3>5. Website availability and liability</h3><p>The parent terms treat website information as provided without general warranties and limit liability subject to applicable law. The preview does not extend a promise of uninterrupted availability, accuracy, or particular commercial results. Final exclusions and limitations require legal approval.</p>
 <h3>6. Information you enter</h3><p>Only enter information you are authorized to use. Do not include passwords, private keys, regulated personal data, or confidential asset records in this demonstration. The preview does not apply iT1’s broad submission-license clause to project-form entries; that clause is an explicit legal-review item, not silently changed parent wording.</p>
 <h3>7. Other agreements and disputes</h3><p>Separate customer contracts remain distinct from website terms. The parent reference selects courts in Maricopa County, Arizona, for disputes. Applicability to this brand, the contracting party, governing-law wording, and mandatory user protections require counsel’s confirmation.</p>
 <h3>8. Changes and contact</h3><p>This preview may change during design review. It has no production effective date. Contact iT1 through its <a href="https://it1.com/contact-us/" target="_blank" rel="noopener noreferrer">published contact page</a> for questions about the parent terms. The linked parent document is the source, not a claim that this draft has been adopted.</p>`},
 cookies:{title:'Cookie Policy',subtitle:'Privacy controls that match this build',source:'https://it1.com/privacy-policy/',sourceName:'iT1 Privacy Policy — parent reference',html:`
 <p class="draft-notice"><strong>Preview-specific draft.</strong> This policy describes the code delivered for executive review. No public-production cookie inventory or legal compliance certification is represented.</p>
 <h3>What this website stores</h3><p>This preview does not set HTTP cookies. It uses browser local storage to remember privacy choices. Unlike an HTTP cookie, that record is not automatically included in web requests.</p>
 <div class="table-scroll"><table><thead><tr><th>Item</th><th>Purpose</th><th>Duration</th></tr></thead><tbody><tr><td><code>ptr_privacy_v1</code></td><td>Stores policy version, essential/analytics/marketing choices, signal preference, timestamp, and expiry. No unique visitor identifier.</td><td>180 days, checked when the preview opens; removable at any time.</td></tr></tbody></table></div>
 <h3>Necessary, analytics, and marketing</h3><p>The necessary category remembers your preference. Analytics and marketing are optional and default off. No optional vendors exist in this build, even after you accept optional categories. These controls are not a substitute for a production consent-management integration.</p>
 <h3>Choose, reject, or change your mind</h3><p>Use the notice’s Essential only action to decline both optional categories, or save individual choices in Cookie preferences. The footer and small privacy button reopen preferences. Withdrawing a choice changes the stored record immediately. Because there are no optional scripts or cookies here, there are no vendor trackers to disable or delete.</p>
 <h3>Browser privacy signals</h3><p>This implementation checks Global Privacy Control and Do Not Track. When either is enabled, optional choices remain off and their switches cannot be enabled. The preference panel shows that a signal is active. This applies only to this preview; it does not submit an account-level rights request to iT1.</p>
 <h3>Storage unavailable or expired</h3><p>If your browser blocks local storage, the website still works and keeps the choice in memory for the current page. It will ask again on a later visit. Malformed, unrecognized, or expired records are ignored and optional choices return to off.</p>
 <h3>What changes before production</h3><p>The parent website describes advertising, shopping-cart, and analytics technologies. Those are not installed here. Before adding any vendor, the team must document its purpose, identifiers, lifetime, recipients, and consent behavior; test that it cannot load before permission; implement withdrawal and signal handling; and update this notice. External iT1 links open a separate site governed by that site’s policies.</p>`},
 accessibility:{title:'Accessibility Statement',subtitle:'Our approach to an accessible experience',source:'https://www.w3.org/TR/WCAG22/',sourceName:'W3C Web Content Accessibility Guidelines 2.2',html:`
 <p class="draft-notice"><strong>Design and testing statement.</strong> The target is WCAG 2.2 Level AA. A target is not a conformance claim, certification, or completed third-party audit.</p>
 <h3>Included in this preview</h3><p>The homepage uses semantic landmarks and headings, a skip link, keyboard-operable controls, visible focus indicators, labeled forms, native dialogs, data-table headers, and text alternatives for meaningful imagery. Animation is minimized when the browser requests reduced motion. Content reflows for narrower screens.</p>
 <h3>Interactive content</h3><p>Services and industries can be explored by keyboard. Privacy settings, legal documents, and the project form open in dialogs with named headings and close controls. Press Escape to close a dialog. Table filtering includes an empty state and status updates for assistive technology.</p>
 <h3>Review still required</h3><p>Before launch, complete assistive-technology testing across the agreed browser and device matrix, contrast and zoom checks, keyboard-order review, mobile checks, and review of the final copy, documents, media, and integrations. An authentic production contact channel and remediation owner must be approved.</p>
 <h3>Request help or report a barrier</h3><p>For this executive review, send feedback to the project owner. For the parent company, use <a href="https://it1.com/contact-us/" target="_blank" rel="noopener noreferrer">iT1’s contact page</a> or call <a href="tel:+18777775995">(877) 777-5995</a>. Describe the page, task, browser, and difficulty without including sensitive information.</p>`}
};
