"""Exercise the cinematic journey through real scrolling, links, and controls."""
import argparse, json
from pathlib import Path
from playwright.sync_api import sync_playwright

parser=argparse.ArgumentParser()
parser.add_argument('--url',required=True)
parser.add_argument('--output',required=True)
args=parser.parse_args()
out=Path(args.output);out.mkdir(parents=True,exist_ok=True)
checks=[];errors=[]
def check(name,ok):
    checks.append({'name':name,'passed':bool(ok)})
    assert ok,name

with sync_playwright() as p:
    browser=p.chromium.launch()
    page=browser.new_page(viewport={'width':1536,'height':1024},reduced_motion='no-preference')
    page.on('pageerror',lambda e:errors.append(str(e)))
    def state():return page.evaluate('PTR_JOURNEY.status')
    def digest(selector):return page.locator(selector).evaluate("c=>{const d=c.getContext('2d').getImageData(0,0,c.width,c.height).data;let h=0;for(let i=0;i<d.length;i+=197)h=(Math.imul(h,31)+d[i])|0;return h;}")
    def chapter(id):
        page.locator('.journey-chapters a[href="#'+id+'"]').click()
        page.wait_for_timeout(1200)
    try:
        response=page.goto(args.url,wait_until='networkidle')
        page.wait_for_function('window.PTR_JOURNEY?.version === "5.0.2"')
        check('Cinematic website loads',response.status==200 and 'Handled.' in page.locator('h1').inner_text())
        check('All three chapters are present',page.locator('[data-journey-scene]').count()==3)
        page.locator('#reject-cookies').click();page.wait_for_timeout(4700)
        check('Chapter navigation waits until the journey begins',not page.locator('.journey-nav').is_visible())
        page.screenshot(path=str(out/'opening.png'))
        page.locator('.hero-journey-entry').click();page.wait_for_timeout(1200)
        check('Entry link reaches protection',page.url.endswith('#protect') and page.locator('.journey-nav').is_visible())
        check('Protection chapter is identified accessibly',page.locator('.journey-chapters a[href="#protect"]').get_attribute('aria-current')=='step')
        pixels=digest('#protect canvas');page.wait_for_timeout(700)
        check('Protection scene remains alive while idle',pixels!=digest('#protect canvas'))
        before=page.evaluate('scrollY');initial=float(page.locator('#protect .cinema-stage').get_attribute('data-camera-progress'))
        page.mouse.move(1300,520);page.mouse.wheel(0,280);page.wait_for_timeout(800)
        after=page.evaluate('scrollY');progress=float(page.locator('#protect .cinema-stage').get_attribute('data-camera-progress'))
        check('Native wheel scrolling advances the journey',after>before+200)
        check('Scroll advances the camera',progress>initial+.1)
        check('Protection stage stays in view during camera movement',abs(page.locator('#protect .cinema-stage').bounding_box()['y']-88)<3)
        page.screenshot(path=str(out/'protect.png'))
        page.mouse.wheel(0,-180);page.wait_for_timeout(700)
        check('Visitors can reverse the journey freely',page.evaluate('scrollY')<after-100)
        check('Camera responds to reverse scrolling',float(page.locator('#protect .cinema-stage').get_attribute('data-camera-progress'))<progress)
        page.locator('.journey-pause').click();page.wait_for_timeout(150)
        pixels=digest('#protect canvas');frames=state()['scenes'][0]['frames'];page.wait_for_timeout(500)
        check('Global pause freezes the actual cinematic canvas',pixels==digest('#protect canvas') and state()['scenes'][0]['frames']==frames)
        check('Global pause also stops the original ambient scenes',page.evaluate('PTR_MOTION.status.paused'))
        page.locator('.journey-pause').press('Enter');page.wait_for_timeout(400)
        check('Keyboard resumes the experience',state()['running'] and state()['scenes'][0]['frames']>frames)
        chapter('recover')
        check('Recovery link selects its chapter',page.url.endswith('#recover') and page.locator('.journey-chapters a[href="#recover"]').get_attribute('aria-current')=='step')
        page.mouse.wheel(0,240);page.wait_for_timeout(700)
        page.screenshot(path=str(out/'recover.png'))
        pixels=digest('#recover canvas');page.wait_for_timeout(500)
        check('Recovery has a live rendered scene',pixels!=digest('#recover canvas'))
        page.get_by_role('button',name='Explore value recovery',exact=True).click()
        check('Cinematic CTA opens relevant service details','remarketing' in page.locator('#content-title').inner_text().lower())
        page.wait_for_timeout(100)
        check('Open dialogs suspend cinematic rendering',not state()['running'])
        page.locator('#content-dialog [data-close]').click();page.wait_for_timeout(200)
        check('Closing the dialog restores the live scene',state()['running'])
        chapter('sustainability')
        page.mouse.wheel(0,240);page.wait_for_timeout(700)
        check('Renewal link selects its chapter',page.locator('.journey-chapters a[href="#sustainability"]').get_attribute('aria-current')=='step')
        check('Forest image is loaded',page.locator('.reuse-image img').evaluate('i=>i.complete&&i.naturalWidth>0'))
        page.screenshot(path=str(out/'renew.png'))
        transform=page.locator('.reuse-image img').evaluate('i=>getComputedStyle(i).transform')
        page.mouse.wheel(0,230);page.wait_for_timeout(650)
        check('Forest camera changes with scrolling',transform!=page.locator('.reuse-image img').evaluate('i=>getComputedStyle(i).transform'))
        check('Offscreen geometric scenes stop rendering',not state()['running'])
        chapter('protect');page.emulate_media(reduced_motion='reduce');page.wait_for_timeout(350)
        before=float(page.locator('#protect .cinema-stage').get_attribute('data-camera-progress'))
        page.mouse.wheel(0,230);page.wait_for_timeout(600)
        check('Explicit full experience remains enabled with OS reduced motion',state()['running'] and float(page.locator('#protect .cinema-stage').get_attribute('data-camera-progress'))>before)
        page.locator('.journey-pause').press('Space');page.wait_for_timeout(100)
        check('Manual pause is available with reduced motion',state()['paused'] and not state()['running'])
        page.locator('.journey-pause').click()
        # Chapter navigation visibility must never change document height at the footer.
        # Otherwise short footers can oscillate across the navigation threshold.
        for height in [1000,1100,1200]:
            page.set_viewport_size({'width':1440,'height':height})
            page.get_by_role('link',name='Privacy Policy',exact=True).click()
            page.locator('#content-dialog').wait_for(state='visible')
            check(f'Footer privacy link remains clickable at {height}px',page.locator('#content-dialog').is_visible())
            page.locator('#content-dialog [data-close]').click();page.wait_for_timeout(700)
            before=page.evaluate('scrollY');page.wait_for_timeout(400)
            check(f'Footer scroll position is stable at {height}px',abs(page.evaluate('scrollY')-before)<1)
            check(f'Chapter rail stays clear of the footer at {height}px',not page.locator('.journey-nav').is_visible())
        for width,height in [(320,740),(390,844),(768,1024),(1024,768),(1440,900),(1920,1080)]:
            page.set_viewport_size({'width':width,'height':height});page.wait_for_timeout(200)
            check(f'No horizontal overflow at {width} by {height}',page.evaluate('document.documentElement.scrollWidth<=innerWidth+1'))
        page.set_viewport_size({'width':1280,'height':720})
        page.get_by_role('link',name='Phoenix Tech Refresh home',exact=True).first.click()
        page.locator('.hero-journey-entry').click();page.wait_for_timeout(700)
        chapter('recover')
        before=float(page.locator('#recover .cinema-stage').get_attribute('data-camera-progress'))
        check('Short desktop view has an intermediate camera position',.1<before<.8)
        page.mouse.wheel(0,160);page.wait_for_timeout(500)
        after=float(page.locator('#recover .cinema-stage').get_attribute('data-camera-progress'))
        check('Short desktop scrolling advances the camera continuously',before+.04<after<.95)
        phone=browser.new_page(viewport={'width':390,'height':844},is_mobile=True,has_touch=True,reduced_motion='reduce')
        phone.on('pageerror',lambda e:errors.append(str(e)))
        phone.goto(args.url,wait_until='networkidle');phone.locator('#reject-cookies').click();phone.wait_for_timeout(4700)
        phone.locator('.hero-journey-entry').tap();phone.wait_for_timeout(900)
        check('Touch users can enter the journey',phone.url.endswith('#protect') and phone.locator('.journey-nav').is_visible())
        phone.screenshot(path=str(out/'mobile-protect.png'))
        phone.locator('.journey-chapters a[href="#recover"]').tap();phone.wait_for_timeout(900)
        check('Mobile chapter navigation works',phone.locator('.journey-chapters a[href="#recover"]').get_attribute('aria-current')=='step')
        phone.screenshot(path=str(out/'mobile-recover.png'))
        phone.locator('.journey-pause').tap();phone.wait_for_timeout(100)
        check('Touch pause stops the cinematic scene',phone.evaluate('PTR_JOURNEY.status.paused && !PTR_JOURNEY.status.running'))
        phone.locator('.journey-pause').tap()
        phone.locator('.journey-chapters a[href="#sustainability"]').tap();phone.wait_for_timeout(900)
        phone.screenshot(path=str(out/'mobile-renew.png'))
        phone.get_by_role('button',name='Rethink what retirement means',exact=True).tap()
        check('Mobile renewal CTA remains usable',phone.locator('#content-dialog').is_visible())
        check('No runtime errors',not errors)
    finally:
        (out/'results.json').write_text(json.dumps({'checks':checks,'errors':errors},indent=2))
        print(json.dumps({'passed':sum(c['passed'] for c in checks),'total':len(checks),'errors':errors}),flush=True)
        browser.close()
