"""User-flow regression coverage for the redesigned static homepage."""
import argparse, json
from pathlib import Path
from playwright.sync_api import sync_playwright

parser=argparse.ArgumentParser()
parser.add_argument('--url',required=True)
parser.add_argument('--output',required=True)
args=parser.parse_args()
out=Path(args.output);out.mkdir(parents=True,exist_ok=True)
checks=[];errors=[]
def check(name,ok):
    checks.append({'name':name,'passed':bool(ok)})
    assert ok,name

with sync_playwright() as p:
    browser=p.chromium.launch()
    page=browser.new_page(viewport={'width':1536,'height':1024})
    page.on('pageerror',lambda e:errors.append(str(e)))
    try:
        response=page.goto(args.url,wait_until='networkidle')
        check('Homepage responds successfully',response.status==200)
        check('Correct page and meaningful first screen','Phoenix Tech Refresh' in page.title() and 'Handled.' in page.locator('h1').inner_text())
        page.evaluate('() => document.fonts.ready')
        check('Local display font loads',page.evaluate("() => document.fonts.check('500 16px Manrope')"))
        check('No framework error overlay',page.locator('vite-error-overlay,nextjs-portal').count()==0)
        page.locator('#reject-cookies').click()
        page.wait_for_timeout(4700)
        page.screenshot(path=str(out/'desktop.png'))
        page.locator('[data-service-next]').click()
        check('Next service updates both detail and selection','DATA DESTRUCTION' in page.locator('#feature-label').inner_text() and page.locator('.service-row').nth(1).get_attribute('aria-pressed')=='true')
        page.locator('[data-service-prev]').click()
        page.locator('[data-service-prev]').click()
        check('Previous service wraps to final service',page.locator('#service-position').inner_text()=='08 — 08' and 'BUYBACK' in page.locator('#feature-label').inner_text())
        page.locator('#service-detail-button').click()
        check('Selected service detail opens','Buyback' in page.locator('#content-title').inner_text())
        page.locator('#content-dialog [data-quote]').click()
        check('Service passes into quote flow','Buyback' in page.locator('#q-service').input_value())
        page.locator('#q-volume').select_option(label='50–249')
        page.locator('#q-location').fill('Phoenix, AZ')
        page.locator('#q-timing').select_option(label='Planning ahead')
        page.locator('#quote-next').click()
        check('Project advances to details',page.locator('#quote-step-2').is_visible())
        page.locator('#q-name').fill('Website QA')
        page.locator('#q-company').fill('Example Test Company')
        page.locator('#q-email').fill('qa@example.com')
        page.locator('#quote-review').click()
        check('Review contains entered project details','Example Test Company' in page.locator('#quote-summary').inner_text() and 'Phoenix, AZ' in page.locator('#quote-summary').inner_text())
        check('Inquiry remains explicitly unsent','not sent' in page.locator('#quote-step-3').inner_text().lower().replace('—',' ').replace('–',' ').replace('-',' '))
        with page.expect_download() as dl:page.locator('#quote-download').click()
        check('Project summary downloads',dl.value.suggested_filename=='Phoenix-project-summary.txt')
        page.locator('#quote-dialog [data-close]').click()
        page.locator('#process-tab-0').click()
        page.locator('#process-tab-0').press('ArrowRight')
        check('Keyboard changes lifecycle step and number',page.locator('#process-number').inner_text()=='02' and page.locator('#process-tab-1').get_attribute('aria-selected')=='true')
        page.locator('#process-tab-1').press('End')
        check('Keyboard jumps to final lifecycle step',page.locator('#process-number').inner_text()=='06')
        page.locator('#asset-search').fill('DEMO-LT')
        check('Search filters demonstration assets',page.locator('#asset-rows tr').count()==2)
        page.locator('#asset-status').select_option(label='Testing & grading')
        check('Combined filters show empty state','No demo assets' in page.locator('#asset-rows').inner_text())
        page.locator('#asset-search').fill('')
        check('Status filter shows matching server',page.locator('#asset-rows tr').count()==1 and 'Rack server' in page.locator('#asset-rows').inner_text())
        with page.expect_download() as dl:page.locator('#export-assets').click()
        check('Filtered sample export downloads',dl.value.suggested_filename=='Phoenix-DEMO-assets.csv')
        page.locator('#portal-value').click()
        check('Value tab explains synthetic figures','synthetic example' in page.locator('#portal-panel').inner_text().lower())
        page.locator('#industry-tab-1').click()
        check('Industry selection updates tab',page.locator('#industry-tab-1').get_attribute('aria-selected')=='true')
        page.locator('#resource-grid [data-resource]').first.click()
        check('Editorial tile opens reading content',page.locator('#content-dialog').is_visible() and 'Before your next hardware refresh' in page.locator('#content-title').inner_text())
        page.locator('#content-dialog [data-close]').click()
        page.locator('.faqs summary').first.click()
        check('FAQ expands with readable answer',page.locator('.faqs details').first.get_attribute('open') is not None)
        for section in ['services','process','portal','sustainability','why-phoenix','industries','resources','faq','contact']:
            page.locator('#'+section).scroll_into_view_if_needed();page.wait_for_timeout(850)
            page.locator('#'+section).screenshot(path=str(out/(section+'.png')))
        check('All page imagery loads',page.evaluate('() => [...document.images].every(i => i.complete && i.naturalWidth>0)'))
        page.set_viewport_size({'width':390,'height':844})
        page.goto(args.url,wait_until='networkidle');page.wait_for_timeout(1500)
        page.screenshot(path=str(out/'mobile.png'))
        page.locator('#mobile-menu-toggle').click()
        check('Mobile menu opens',page.locator('#mega-menu').is_visible())
        page.locator('#mega-menu a[href="#industries"]').click()
        check('Mobile navigation closes after selection',page.locator('#mega-menu').is_hidden() and page.url.endswith('#industries'))
        for section in ['services','portal','sustainability','contact']:
            page.locator('#'+section).scroll_into_view_if_needed();page.wait_for_timeout(850)
            check('Mobile '+section+' fits viewport',page.evaluate('() => document.documentElement.scrollWidth <= innerWidth+1'))
            page.locator('#'+section).screenshot(path=str(out/('mobile-'+section+'.png')))
        check('No runtime errors',not errors)
    finally:
        (out/'results.json').write_text(json.dumps({'checks':checks,'errors':errors},indent=2))
        print(json.dumps({'passed':sum(c['passed'] for c in checks),'total':len(checks),'errors':errors}))
        browser.close()
